print("hello temitope")
print("monkey is a mammal")
print("am doing fine today")
print("getting it right now")
print("home is home runing out of time")
print("omo or omo is a soup")
print("nnena what have you done")
