print("hello temitope")
print("monkey is a mammal")
print("am doing fine today")
print("getting it right now")
print("danger danger dog is here")
print("danger is not actually the dog is here")
print("danger danger dog is here")
